# Site Settings
title: "Let's Talk Podcasts"
support_links:
  - title: "Patreon"
    button_text: "Monthly Patreon Pledge"
    support_page_text: "A monthly Subscription on"
    url: "https://www.patreon.com/ltpod"
    icon: "fa-brands fa-patreon"
  - title: "PayPal"
    button_text: "One-Time PayPal Donation"
    support_page_text: "A one-time donation via"
    url: "https://www.paypal.com/donate/?hosted_button_id=HEYHNGKY8EASE"
    icon: "fa-brands fa-paypal"
subscription_types:
  - title: "RSS Feed"
    type: rss
    icon: "fa-solid fa-rss"
  - title: "Apple Podcasts"
    type: apple_podcasts
    icon: "fa-brands fa-apple"
  - title: "Podcast Index"
    type: podcast_index
    icon: "fa-solid fa-podcast"
socialmedia_platforms:
  x:
    title: X
    icon: "fa-brands fa-square-x-twitter"
    profile_url_prefix: "https://x.com/"
    handle_prefix: "@"
  flickr:
    title: Flickr
    icon: "fa-brands fa-flickr"
    profile_url_prefix: "https://flickr.com/photos/"
  bluesky:
    title: Bluesky
    icon: "fa-brands fa-square-bluesky"
    profile_url_prefix: "https://bsky.app/profile/"
    handle_prefix: "@"
  mastodon:
    title: Mastodon
    icon: "fa-brands fa-mastodon"
  glass:
    title: Glass
    icon: "fa-solid fa-images"
    profile_url_prefix: "https://glass.photo/"
  github:
    title: GitHub
    icon: "fa-brands fa-square-github"
    profile_url_prefix: "https://github.com/"

# Build Settings
plugins:
  - jekyll-autoprefixer

# Settings for the autoprefixer plugin
autoprefixer:
  browsers:
    - last 4 versions
    - Safari > 2

# Define collections
# Note: in collection permalinks, :title defaults to the slug from the front matter
collections:
  contributors:
    output: true
    permalink: /contributor/:title
    sort_by: sort_name
  podcasts:
    output: true
    permalink: /:title
    sort_by: slug
  lta:
    output: true
    permalink: /:title
    sort_by: slug
  ltp:
    output: true
    permalink: /:title
    sort_by: slug

# Configure front matter defaults
defaults:
  - scope:
      path: ""
      type: podcasts
    values:
      layout: podcast
  - scope:
      path: ""
      type: lta
    values:
      layout: podcast_episode
  - scope:
      path: ""
      type: ltp
    values:
      layout: podcast_episode
  - scope:
      path: ""
      type: contributors
    values:
      layout: contributor