# Site Settings
title: "Let's Talk Podcasts"
support_links:
  - title: "Patreon"
    button_text: "Monthly Patreon Pledge"
    support_page_text: "A monthly Subscription on"
    url: "https://www.patreon.com/ltpod"
    icon: "fa-brands fa-patreon"
  - title: "PayPal"
    button_text: "One-Time PayPal Donation"
    support_page_text: "A one-time donation via"
    url: "https://www.paypal.com/donate/?hosted_button_id=HEYHNGKY8EASE"
    icon: "fa-brands fa-paypal"

# Build Settings
plugins:
  - jekyll-autoprefixer

# Settings for the autoprefixer plugin
autoprefixer:
  browsers:
    - last 4 versions
    - Safari > 2

# Define collections
# Note: in collection permalinks, :title defaults to the slug from the front matter
collections:
  contributors:
    output: true
    permalink: /contributor/:title
    sort_by: sort_name
  podcasts:
    output: true
    permalink: /:title
    sort_by: slug
  lta:
    output: true
    permalink: /:title
    sort_by: slug
  ltp:
    output: true
    permalink: /:title
    sort_by: slug

# Configure front matter defaults
defaults:
  - scope:
      path: ""
      type: podcasts
    values:
      layout: podcast
  - scope:
      path: ""
      type: lta
    values:
      layout: podcast_episode
  - scope:
      path: ""
      type: ltp
    values:
      layout: podcast_episode
  - scope:
      path: ""
      type: contributors
    values:
      layout: contributor